development:
 secret_key_base: <%= ENV["SECRET_KEY_DEV"] %>
test:
 secret_key_base: <%= ENV["SECRET_KEY_TEST"] %>
production:
 secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

 development:
 GMAIL_USERNAME: it.colaveco@gmail.com
 GMAIL_PASSWORD: 19912021ITCOLAVECO
 
test:
 GMAIL_USERNAME: it.colaveco@gmail.com
 GMAIL_PASSWORD: 19912021ITCOLAVECO
 
production:
 GMAIL_USERNAME: it.colaveco@gmail.com
 GMAIL_PASSWORD: 19912021ITCOLAVECO